architect:
- yegor256
- davvd
install:
- sudo gem install pdd
assets:
  secring.gpg: yegor256/home#assets/secring.gpg
  settings.xml: yegor256/home#assets/qulice/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  s3cfg: yegor256/home#assets/s3cfg
merge:
  script: |-
    mvn clean install -Pqulice-profile -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=/dev/null --exclude=qulice-maven-plugin/src/it/**/*.java
  commanders:
  - alevohin
  - carlosmiranda
  - darkled
  - ggajos
  - krzyk
  - longtimeago
  - pinaf
  - yegor256
deploy:
  script: |-
    mvn clean deploy -Pqulice-profile -Pqulice --errors --settings ../settings.xml
    mvn clean
    pdd --source=$(pwd) --verbose --file=qulice.xml --exclude=qulice-maven-plugin/src/it/**/*.java
    s3cmd --no-progress put qulice.xml --config=../s3cfg s3://pdd.teamed.io/qulice.xml
  commanders:
  - yegor256
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice-profile -Pqulice -Psonatype --errors --settings ../settings.xml
    mvn clean site-deploy -Pgh-pages -Pqulice-profile -Psite --errors --settings ../settings.xml || echo 'site-deploy failed'
  commanders:
  - yegor256